//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class booktour
    {
        public string fullname { get; set; }
        public string email { get; set; }
        public int phonenumber { get; set; }
        public string message { get; set; }
    }
}
