// <auto-generated />
namespace DMS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alter_for_gallerydata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_for_gallerydata));
        
        string IMigrationMetadata.Id
        {
            get { return "202207171104339_alter_for_gallerydata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
